-- MySQL Script generated by MySQL Workbench
-- Mon Jun 17 09:27:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema agenda
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `agenda` ;

-- -----------------------------------------------------
-- Schema agenda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agenda` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema al_motors
-- -----------------------------------------------------
USE `agenda` ;

-- -----------------------------------------------------
-- Table `agenda`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agenda`.`rol` ;

CREATE TABLE IF NOT EXISTS `agenda`.`rol` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenda`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agenda`.`usuario` ;

CREATE TABLE IF NOT EXISTS `agenda`.`usuario` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `apePaterno` VARCHAR(50) NULL,
  `apeMaterno` VARCHAR(50) NULL,
  `email` VARCHAR(50) NULL,
  `password` VARCHAR(20) NULL,
  `telefono` VARCHAR(10) NULL,
  `fechaNac` DATE NULL,
  `rolFk` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_rol1_idx` (`rolFk` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rolFk`)
    REFERENCES `agenda`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenda`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agenda`.`empresa` ;

CREATE TABLE IF NOT EXISTS `agenda`.`empresa` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `encargadoFk` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empresa_usuario_idx` (`encargadoFk` ASC) VISIBLE,
  CONSTRAINT `fk_empresa_usuario`
    FOREIGN KEY (`encargadoFk`)
    REFERENCES `agenda`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenda`.`mantenimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agenda`.`mantenimiento` ;

CREATE TABLE IF NOT EXISTS `agenda`.`mantenimiento` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(150) NULL,
  `descripcion` VARCHAR(500) NULL,
  `fechaRegistro` DATE NULL,
  `costo` FLOAT NULL,
  `estadoPago` VARCHAR(50) NULL,
  `empresaFk` INT NOT NULL,
  `clienteFk` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mantenimiento_empresa1_idx` (`empresaFk` ASC) VISIBLE,
  INDEX `fk_mantenimiento_usuario1_idx` (`clienteFk` ASC) VISIBLE,
  CONSTRAINT `fk_mantenimiento_empresa1`
    FOREIGN KEY (`empresaFk`)
    REFERENCES `agenda`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mantenimiento_usuario1`
    FOREIGN KEY (`clienteFk`)
    REFERENCES `agenda`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Insertar datos en la tabla `rol`
-- -----------------------------------------------------
INSERT INTO `agenda`.`rol` (`id`, `nombre`) VALUES
(1, 'Mecánico'),
(2, 'Cliente');

-- -----------------------------------------------------
-- Insertar datos en la tabla `usuario`
-- -----------------------------------------------------
INSERT INTO `agenda`.`usuario` (`id`, `nombre`, `apePaterno`, `apeMaterno`, `email`, `password`, `telefono`, `fechaNac`, `rolFk`) VALUES
(1, 'John', 'Doe', 'Smith', 'john.doe@example.com', 'password123', '1234567890', '1990-01-01', 1),
(2, 'Jane', 'Doe', 'Johnson', 'jane.doe@example.com', 'password456', '0987654321', '1992-02-02', 2);

-- -----------------------------------------------------
-- Insertar datos en la tabla `empresa`
-- -----------------------------------------------------
INSERT INTO `agenda`.`empresa` (`id`, `nombre`, `encargadoFk`) VALUES
(1, 'Tech Solutions', 1),
(2, 'Business Corp', 2);

-- -----------------------------------------------------
-- Insertar datos en la tabla `mantenimiento`
-- -----------------------------------------------------
INSERT INTO `agenda`.`mantenimiento` (`id`, `nombre`, `descripcion`, `fechaRegistro`, `costo`, `estadoPago`, `empresaFk`, `clienteFk`) VALUES
(1, 'Reparación de Servidor', 'Reparación completa del servidor principal', '2024-06-10', 500.00, 'Pagado', 1, 2),
(2, 'Actualización de Software', 'Actualización del software de gestión empresarial', '2024-06-15', 300.00, 'Pendiente', 2, 1);

